import {motion,useScroll,useTransform} from 'framer-motion';
import {ArrowRight,ArrowUpRight,Bell,Check,MapPin,PackageOpen,Sparkles} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {getProduct,products} from './data/products';
import {Eyebrow,ImageSlot,Reveal,SectionTitle} from './components/ui';
import ProductCard from './components/ProductCard';

const ease=[.22,1,.36,1] as const;
const platforms=['Amazon India','Flipkart','Blinkit','Zepto','Swiggy Instamart','BigBasket'];
function SoonLink({dark=false}:{dark?:boolean}){return <Link className={dark?'btn btn-light':'btn'} to="/where-to-buy">NOTIFY ME AT LAUNCH <ArrowRight/></Link>}

export function LaunchHome(){const {scrollYProgress}=useScroll();const drift=useTransform(scrollYProgress,[0,.3],[0,42]);return <>
  <section className="launch-hero"><motion.div className="launch-hero-media" style={{y:drift}} initial={{opacity:0,scale:1.04}} animate={{opacity:1,scale:1}} transition={{duration:1.2,ease}}><ImageSlot src="/assets/shams/hero/hero-main.webp" alt="Sham's Masala Chai with a freshly brewed glass" ratio="16 / 9"/></motion.div><div className="launch-hero-shade"/><motion.div className="launch-hero-copy" initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{delay:.25,duration:.9,ease}}><Eyebrow>THE EVERYDAY INDIAN CUP</Eyebrow><h1>CHAI, JUST<br/>AS YOU <em>KNOW IT.</em></h1><p>Bold tea. Handpicked spices. The comfort of a properly brewed Indian cup.</p><div><Link className="btn btn-light" to="/products/masala-chai">MEET MASALA CHAI <ArrowRight/></Link><Link className="hero-quiet-link" to="/our-story">OUR STORY</Link></div></motion.div><motion.div className="hero-seal" initial={{scale:0,rotate:-30}} animate={{scale:1,rotate:0}} transition={{delay:.8,duration:.7,ease}}><span>ARRIVING</span><b>SOON</b><span>ACROSS INDIA</span></motion.div></section>
  <section className="launch-intro"><Reveal><Eyebrow>ONE CHAI. MADE PROPERLY.</Eyebrow><h2>The familiar cup,<br/><em>given its due.</em></h2><p>Sham’s begins with one deeply considered Masala Chai — aromatic, comforting and made for the way India already drinks it.</p></Reveal><div className="launch-intro-notes"><span>01<br/><b>LOOSE LEAF</b></span><span>02<br/><b>HANDPICKED SPICES</b></span><span>03<br/><b>EVERYDAY CHAI</b></span></div></section>
  <section className="single-product"><motion.div initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.8,ease}}><ImageSlot src="/assets/shams/products/masala-pack.webp" alt="Sham's Masala Chai 200 g pack" ratio="1 / 1"/></motion.div><Reveal className="single-product-copy"><Eyebrow>THE FIRST BLEND</Eyebrow><h2>SHAM’S<br/><em>MASALA CHAI</em></h2><div className="flavour-line"><span>BOLD</span><i/><span>AROMATIC</span><i/><span>COMFORTING</span></div><p>A warm, layered blend of premium tea leaves and handpicked spices. Made to hold its own with milk, conversation and the second cup.</p><div className="pack-badge"><PackageOpen/><span><b>200 g</b> LOOSE LEAF CHAI</span></div><Link to="/products/masala-chai" className="text-link">DISCOVER THE BLEND <ArrowRight/></Link></Reveal></section>
  <section className="memory-statement"><Reveal><span>BEFORE MEETINGS.</span><span>AFTER RAIN.</span><span>BETWEEN CONVERSATIONS.</span><strong>THERE WAS ALWAYS CHAI.</strong></Reveal></section>
  <section className="launch-moments"><SectionTitle eyebrow="A CUP FOR THE MOMENT" title="However the day finds you."/><div className="launch-moment-grid">{[['AT HOME','The first sound in the kitchen.','lifestyle-home.webp'],['WHEN IT RAINS','A slower hour by the window.','lifestyle-rain.webp'],['BETWEEN US','Conversations that outlast the kettle.','lifestyle-together.webp']].map((m,i)=><motion.article key={m[0]} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:i*.12,duration:.7,ease}}><ImageSlot src={`/assets/shams/lifestyle/${m[2]}`} alt={m[0]} ratio="2 / 3"/><span>0{i+1}</span><h3>{m[0]}</h3><p>{m[1]}</p></motion.article>)}</div></section>
  <section className="launch-brew"><div><Eyebrow>THE SHAMS METHOD</Eyebrow><h2>YOUR KITCHEN.<br/><em>YOUR RULES.</em></h2><p>Begin with our six-step method. Then make it stronger, milkier or sweeter until it tastes like yours.</p><Link to="/brew-guide" className="text-link">HOW TO BREW <ArrowRight/></Link></div><div className="brew-orbit"><span>01 <b>BOIL</b></span><span>02 <b>ADD SHAMS</b></span><span>03 <b>SWEETEN</b></span><span>04 <b>ADD MILK</b></span><span>05 <b>SIMMER</b></span><span>06 <b>STRAIN</b></span><i>〰</i></div></section>
  <section className="launch-platform"><Reveal><Eyebrow>ARRIVING SOON</Eyebrow><h2>FIND SHAM’S<br/><em>WHERE YOU ALREADY SHOP.</em></h2><p>We’re preparing to launch on leading marketplaces and quick-commerce platforms across India.</p><SoonLink dark/></Reveal><div className="platform-ribbon">{platforms.map((p,i)=><motion.span key={p} initial={{opacity:0,x:25}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.06}}>{p}<small>COMING SOON</small></motion.span>)}</div></section>
  <section className="launch-gift"><ImageSlot src="/assets/shams/gifting/gift-main.webp" alt="Sham's chai gifting" ratio="2 / 3"/><Reveal><Eyebrow>SHAMS GIFTING</Eyebrow><h2>A GOOD CUP<br/>IS A GOOD <em>GESTURE.</em></h2><p>Thoughtful chai gifting for visits, festivals, teams and the people who always stay for another cup.</p><Link to="/gifting" className="text-link">EXPLORE GIFTING <ArrowRight/></Link></Reveal></section>
  <section className="launch-notify"><Sparkles/><Eyebrow>BE THE FIRST TO POUR</Eyebrow><h2>SHAM’S IS<br/><em>ALMOST READY.</em></h2><p>Leave your email and we’ll tell you when Masala Chai lands on leading platforms.</p><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="YOUR EMAIL ADDRESS"/><button><Bell/> NOTIFY ME</button></form><small>No noise. Just the launch note.</small></section>
  </>}

export function LaunchProducts(){return <><section className="launch-page-head"><Eyebrow>OUR CHAI</Eyebrow><h1>ONE BLEND.<br/><em>ENDLESS CUPS.</em></h1><p>We’re starting with the chai at the heart of it all.</p></section><section className="launch-catalog"><div><ProductCard product={products[0]}/></div><aside><span>01 / 01</span><h2>Why begin<br/>with Masala?</h2><p>Because familiarity is a serious place to start. A balanced everyday masala chai lets the tea stay bold while the spices arrive warmly — never loudly.</p><Link to="/products/masala-chai" className="text-link">EXPLORE MASALA CHAI <ArrowRight/></Link></aside></section></>}

export function LaunchProduct(){const {slug}=useParams();const p=getProduct(slug);if(!p)return <LaunchProducts/>;return <><section className="launch-pdp"><div className="launch-pdp-gallery"><ImageSlot src={p.images[0]} alt={p.name} ratio="1 / 1"/><ImageSlot src={p.images[1]} alt="Masala chai at home" ratio="2 / 3"/></div><motion.div className="launch-pdp-info" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7,ease}}><Eyebrow>SHAM’S · LOOSE LEAF CHAI</Eyebrow><h1>{p.name}</h1><p className="launch-pdp-sub">{p.subtitle}</p><p>{p.description}</p><div className="launch-pack"><span>PACK</span><b>200 g</b><small>LOOSE LEAF CHAI</small></div><div className="soon-panel"><span>ARRIVING SOON</span><h3>On leading platforms across India.</h3><p>Join the launch list and we’ll share verified availability links as soon as they go live.</p><SoonLink/></div><div className="pdp-facts">{[['FLAVOUR',p.flavourNotes.join(' · ')],['INGREDIENTS',p.ingredients.join(' · ')],['HOW TO BREW','Boil · Add Shams · Sweeten · Add milk · Simmer · Strain']].map(x=><div key={x[0]}><span>{x[0]}</span><p>{x[1]}</p></div>)}</div></motion.div></section></>}

export function Availability(){return <><section className="availability-hero"><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8,ease}}><Eyebrow>WHERE TO FIND SHAM’S</Eyebrow><h1>COMING TO<br/><em>A PLATFORM NEAR YOU.</em></h1><p>Sham’s Masala Chai is preparing to arrive on India’s leading marketplaces and quick-commerce platforms.</p></motion.div></section><section className="availability-grid">{platforms.map((p,i)=><motion.div key={p} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}}><span>0{i+1}</span><h2>{p}</h2><small>COMING SOON</small><ArrowUpRight/></motion.div>)}</section><section className="availability-note"><MapPin/><h2>Across India.<br/><em>One cup at a time.</em></h2><p>Verified links will appear here only when each listing is live.</p><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="YOUR EMAIL ADDRESS"/><button><Check/> JOIN THE LAUNCH LIST</button></form></section></>}

export function FounderLaunch(){const chapters=[
  ['01','THE BEGINNING','Sham’s began with a familiar belief: the chai already present in our homes deserved to be made and presented with real care. Sharmila held onto that simple idea and kept working until it could become something tangible.'],
  ['02','THE WORK BEHIND IT','Building the brand has meant patience, persistence and the unglamorous work that happens long before anyone sees a finished pack. Every decision has asked for another look, another conversation and the determination to keep moving.'],
  ['03','WHY MASALA CHAI','Sharmila chose to begin with one honest, everyday blend. Not to overwhelm people with choice, but to make one cup thoughtfully—bold enough for milk, warmly spiced and familiar from the first sip.'],
  ['04','WHAT COMES NEXT','The work continues: earning a place in Indian kitchens, listening carefully and growing without losing the warmth that made the first cup matter.']
];return <>
  <section className="founder-launch-hero"><motion.div className="founder-launch-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8,ease}}><Eyebrow>FOUNDER · SHAM’S CHAI</Eyebrow><h1>BUILT WITH<br/><em>PATIENCE.</em><br/>POURED WITH<br/><em>PURPOSE.</em></h1><p>Sharmila Krishna Chintapenta is building Sham’s with the quiet determination it takes to turn a deeply personal idea into an everyday Indian brand.</p></motion.div><motion.div className="founder-photo" initial={{opacity:0,scale:1.03}} animate={{opacity:1,scale:1}} transition={{duration:1,ease}}><ImageSlot src="/assets/shams/founder/sharmila-home.webp" alt="Sharmila Krishna Chintapenta" ratio="4 / 5"/><span>REAL FOUNDER PORTRAIT TO BE SUPPLIED</span></motion.div><div className="founder-vertical">SHARMILA KRISHNA CHINTAPENTA · FOUNDER</div></section>
  <section className="founder-belief"><Reveal><Eyebrow>HER BELIEF</Eyebrow><blockquote>“I didn’t want to reinvent chai.<br/><em>I wanted to honour why we love it.”</em></blockquote></Reveal><p>That belief became the standard for Sham’s: respect the ritual, do the work properly and never make the everyday cup feel ordinary.</p></section>
  <section className="founder-chapter-list"><div className="founder-chapter-intro"><Eyebrow>THE STORY SO FAR</Eyebrow><h2>Hard work,<br/><em>held quietly.</em></h2><p>A brand is built in the decisions no one applauds—the revisions, the waiting, the small improvements and the choice to begin again when something is not right.</p></div><div>{chapters.map((c,i)=><motion.article key={c[0]} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.25}} transition={{delay:i*.05,duration:.65,ease}}><span>{c[0]}</span><div><h3>{c[1]}</h3><p>{c[2]}</p></div></motion.article>)}</div></section>
  <section className="founder-signoff"><motion.div initial={{opacity:0,scale:.97}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{duration:.8,ease}}><span>SHAM’S CHAI</span><h2>ONE IDEA.<br/>MANY LONG DAYS.<br/><em>A CUP WORTH SHARING.</em></h2><p>Founded by Sharmila Krishna Chintapenta</p><Link to="/our-story" className="btn btn-light">READ OUR STORY <ArrowRight/></Link></motion.div></section>
  </>}
