import {motion,useScroll,useTransform} from 'framer-motion';
import {ArrowRight,ArrowUpRight,Check,MapPin} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {getProduct,products} from './data/products';
import {Eyebrow,ImageSlot,Reveal,SectionTitle} from './components/ui';
import ProductCard from './components/ProductCard';
import {openLaunchEmail} from './utils/launchMail';

const ease=[.22,1,.36,1] as const;
const heroStagger={hidden:{},show:{transition:{staggerChildren:.12,delayChildren:.38}}};
const heroItem={hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:.75,ease}}};
const heroLine={hidden:{y:'115%'},show:{y:0,transition:{duration:.9,ease}}};
const platforms=['Amazon India','Flipkart','Blinkit','Zepto','Swiggy Instamart','BigBasket'];
function SoonLink({dark=false}:{dark?:boolean}){return <Link className={dark?'btn btn-light':'btn'} to="/checkout">ORDER ON WHATSAPP <ArrowRight/></Link>}
function submitLaunchEmail(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const email=(e.currentTarget.elements.namedItem('email') as HTMLInputElement).value;openLaunchEmail(email)}

export function LaunchHome(){const {scrollYProgress}=useScroll();const drift=useTransform(scrollYProgress,[0,.3],[0,42]);return <>
  <section className="launch-hero">
    <motion.div className="launch-hero-media" style={{y:drift}} initial={{clipPath:'inset(0 0 0 100%)',scale:1.08}} animate={{clipPath:'inset(0 0 0 0%)',scale:1}} transition={{duration:1.35,ease}}><ImageSlot src="/assets/shams/hero/hero-final-pack.png" alt="Sham's Masala Chai beside a freshly brewed glass" ratio="16 / 9"/></motion.div>
    <motion.div className="launch-hero-shade" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:1,delay:.25}}/>
    <motion.div className="launch-hero-copy" variants={heroStagger} initial="hidden" animate="show">
      <motion.div variants={heroItem}><Eyebrow>SHAM’S MASALA CHAI</Eyebrow></motion.div>
      <h1><span className="hero-line"><motion.span variants={heroLine}>A BETTER</motion.span></span><span className="hero-line"><motion.em variants={heroLine}>DAILY CUP.</motion.em></span></h1>
      <motion.div className="hero-actions" variants={heroItem}><Link className="hero-order-link" to="/checkout">ORDER NOW <ArrowRight/></Link></motion.div>
    </motion.div>
  </section>
  <section className="launch-intro home-intro"><Reveal><Eyebrow>MASALA, BALANCED</Eyebrow><h2>Familiar warmth.<br/><em>A finer finish.</em></h2></Reveal><div className="launch-intro-notes"><span>01<br/><b>PREMIUM TEA</b></span><span>02<br/><b>HANDPICKED SPICES</b></span><span>03<br/><b>NO PRESERVATIVES</b></span></div></section>
  <section className="single-product home-product"><motion.div initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.8,ease}}><ImageSlot src="/assets/shams/products/masala-final-pack.png" alt="Sham's Masala Chai pouch" ratio="1 / 1"/></motion.div><Reveal className="single-product-copy"><Eyebrow>THE SIGNATURE BLEND</Eyebrow><h2>SHAM’S<br/><em>MASALA CHAI</em></h2><div className="flavour-line"><span>RICH</span><i/><span>AROMATIC</span><i/><span>WARM SPICE</span></div><div className="home-pack-sizes"><span>200g</span><span>500g</span><span>1000g</span></div><Link to="/checkout" className="btn">ORDER ON WHATSAPP <ArrowRight/></Link></Reveal></section>
  <section className="memory-statement home-statement"><Reveal><span>EVERYDAY RITUAL.</span><strong>BEAUTIFULLY MADE.</strong></Reveal></section>
  <section className="launch-moments home-moments"><SectionTitle eyebrow="CHAI, AS IT HAPPENS" title="Made for the moment."/><div className="launch-moment-grid">{[['AT HOME','home-with-pack-v3.png'],['AFTER RAIN','rain-with-pack-v3.png'],['BETWEEN US','together-with-pack-v4.png']].map((m,i)=><motion.article key={m[0]} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:i*.12,duration:.7,ease}}><ImageSlot src={`/assets/shams/lifestyle/${m[1]}`} alt={`Sham's Masala Chai — ${m[0]}`} ratio="2 / 3"/><span>0{i+1}</span><h3>{m[0]}</h3></motion.article>)}</div></section>
  <section className="launch-brew home-brew"><div><Eyebrow>THE SHAMS METHOD</Eyebrow><h2>BREW IT<br/><em>YOUR WAY.</em></h2><Link to="/brew-guide" className="text-link">SIX SIMPLE STEPS <ArrowRight/></Link></div><div className="brew-orbit"><span>01 <b>BOIL</b></span><span>02 <b>ADD SHAMS</b></span><span>03 <b>SWEETEN</b></span><span>04 <b>ADD MILK</b></span><span>05 <b>SIMMER</b></span><span>06 <b>STRAIN</b></span><i>〰</i></div></section>
  <section className="home-order"><Eyebrow>READY TO POUR?</Eyebrow><h2>Choose your pack.</h2><Link className="btn btn-light" to="/checkout">ORDER DIRECTLY <ArrowRight/></Link></section>
  </>}

export function LaunchProducts(){return <><section className="launch-page-head"><Eyebrow>OUR CHAI</Eyebrow><h1>ONE BLEND.<br/><em>ENDLESS CUPS.</em></h1><p>We’re starting with the chai at the heart of it all.</p></section><section className="launch-catalog"><div><ProductCard product={products[0]}/></div><aside><span>01 / 01</span><h2>Why begin<br/>with Masala?</h2><p>Because familiarity is a serious place to start. A balanced everyday masala chai lets the tea stay bold while the spices arrive warmly — never loudly.</p><Link to="/products/masala-chai" className="text-link">EXPLORE MASALA CHAI <ArrowRight/></Link></aside></section></>}

export function LaunchProduct(){const {slug}=useParams();const p=getProduct(slug);if(!p)return <LaunchProducts/>;return <><section className="launch-pdp"><div className="launch-pdp-gallery"><ImageSlot src={p.images[0]} alt={p.name} ratio="1 / 1"/><ImageSlot src={p.images[1]} alt="Masala chai at home" ratio="2 / 3"/></div><motion.div className="launch-pdp-info" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7,ease}}><Eyebrow>SHAM’S · MASALA CHAI</Eyebrow><h1>{p.name}</h1><p className="launch-pdp-sub">{p.subtitle}</p><p>{p.description}</p><div className="launch-pack"><span>AVAILABLE SIZES</span><b>200g · 500g · 1000g</b><small>PURE &amp; HANDCRAFTED</small></div><div className="soon-panel order-panel"><span>ORDER DIRECTLY</span><h3>Choose your size. Tell us the quantity.</h3><p>Complete the short checkout and send your ready-made order message to us on WhatsApp.</p><div className="pdp-size-links"><Link to="/checkout?size=200g">200g</Link><Link to="/checkout?size=500g">500g</Link><Link to="/checkout?size=1000g">1000g</Link></div><SoonLink/></div><div className="pdp-facts">{[['FLAVOUR',p.flavourNotes.join(' · ')],['INGREDIENTS',p.ingredients.join(' · ')],['HOW TO BREW','Boil · Add Shams · Sweeten · Add milk · Simmer · Strain']].map(x=><div key={x[0]}><span>{x[0]}</span><p>{x[1]}</p></div>)}</div></motion.div></section></>}

export function Availability(){return <><section className="availability-hero"><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8,ease}}><Eyebrow>WHERE TO FIND SHAM’S</Eyebrow><h1>COMING TO<br/><em>A PLATFORM NEAR YOU.</em></h1><p>Sham’s Masala Chai is preparing to arrive on India’s leading marketplaces and quick-commerce platforms.</p></motion.div></section><section className="availability-grid">{platforms.map((p,i)=><motion.div key={p} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}}><span>0{i+1}</span><h2>{p}</h2><small>COMING SOON</small><ArrowUpRight/></motion.div>)}</section><section className="availability-note"><MapPin/><h2>Across India.<br/><em>One cup at a time.</em></h2><p>Verified links will appear here only when each listing is live.</p><form onSubmit={submitLaunchEmail}><input name="email" type="email" placeholder="YOUR EMAIL ADDRESS" autoComplete="email" required/><button type="submit"><Check/> JOIN THE LAUNCH LIST</button></form><small>Opens your email app with a message addressed to support@shamschai.com.</small></section></>}

export function FounderLaunch(){const chapters=[
  ['01','THE BEGINNING','Sham’s began with a familiar belief: the chai already present in our homes deserved to be made and presented with real care. Sharmila held onto that simple idea and kept working until it could become something tangible.'],
  ['02','THE WORK BEHIND IT','Building the brand has meant patience, persistence and the unglamorous work that happens long before anyone sees a finished pack. Every decision has asked for another look, another conversation and the determination to keep moving.'],
  ['03','WHY MASALA CHAI','Sharmila chose to begin with one honest, everyday blend. Not to overwhelm people with choice, but to make one cup thoughtfully—bold enough for milk, warmly spiced and familiar from the first sip.'],
  ['04','WHAT COMES NEXT','The work continues: earning a place in Indian kitchens, listening carefully and growing without losing the warmth that made the first cup matter.']
];return <>
  <section className="founder-launch-hero founder-launch-hero--text"><motion.div className="founder-launch-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8,ease}}><Eyebrow>FOUNDER · SHAM’S CHAI</Eyebrow><h1>BUILT WITH<br/><em>PATIENCE.</em><br/>POURED WITH<br/><em>PURPOSE.</em></h1><p>Sharmila Krishna is building Sham’s with the quiet determination it takes to turn a deeply personal idea into an everyday Indian brand.</p><div className="founder-nameplate"><span>FOUNDED BY</span><strong>Sharmila Krishna</strong><small>AN EVERYDAY INDIAN CHAI BRAND</small></div></motion.div></section>
  <section className="founder-belief"><Reveal><Eyebrow>HER BELIEF</Eyebrow><blockquote>“I didn’t want to reinvent chai.<br/><em>I wanted to honour why we love it.”</em></blockquote></Reveal><p>That belief became the standard for Sham’s: respect the ritual, do the work properly and never make the everyday cup feel ordinary.</p></section>
  <section className="founder-chapter-list"><div className="founder-chapter-intro"><Eyebrow>THE STORY SO FAR</Eyebrow><h2>Hard work,<br/><em>held quietly.</em></h2><p>A brand is built in the decisions no one applauds—the revisions, the waiting, the small improvements and the choice to begin again when something is not right.</p></div><div>{chapters.map((c,i)=><motion.article key={c[0]} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.25}} transition={{delay:i*.05,duration:.65,ease}}><span>{c[0]}</span><div><h3>{c[1]}</h3><p>{c[2]}</p></div></motion.article>)}</div></section>
  <section className="founder-signoff"><motion.div initial={{opacity:0,scale:.97}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{duration:.8,ease}}><span>SHAM’S CHAI</span><h2>ONE IDEA.<br/>MANY LONG DAYS.<br/><em>A CUP WORTH SHARING.</em></h2><p>Founded by Sharmila Krishna</p><Link to="/our-story" className="btn btn-light">READ OUR STORY <ArrowRight/></Link></motion.div></section>
  </>}
