import {FormEvent,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Search as SearchIcon} from 'lucide-react';
import {products} from './data/products';
import {articles,collections} from './data/content';
import ProductCard from './components/ProductCard';
import {Eyebrow,ImageSlot} from './components/ui';
import {whatsappUrl} from './utils/whatsapp';

const PageHero=({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string})=><section className="page-hero"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{copy&&<p>{copy}</p>}</section>;

export function OurStory(){return <><section className="page-hero"><Eyebrow>OUR STORY</Eyebrow><h1>Chai was<br/><em>already here.</em></h1><p>In our kitchens. Between our conversations. Waiting at the end of a long day. Shams began with respect for that everyday cup.</p></section><section className="section story-grid"><ImageSlot src="/assets/shams/optimized/lifestyle-home-v2.webp" alt="Morning chai beside a kettle" ratio="4 / 5" priority/><div><Story n="01" title="Why Shams?">The chai we grew up with, made for the lives we live now. Familiar, dependable and presented with the care an everyday ritual deserves.</Story><Story n="02" title="Built by Sharmila">Sharmila Krishna created Sham’s from a simple belief: the chai already woven into our everyday lives deserves to be made with intention, honesty and care.</Story><Link to="/founder" className="text-link">Meet our founder <ArrowRight/></Link></div></section><section className="section story-dark"><Story n="03" title="The everyday cup">We believe daily things deserve good design, clear choices and consistent quality. Because the everyday cup deserves attention.</Story><Story n="04" title="What comes next">More considered blends, easier ways to find Shams, and a growing journal of the ways India drinks chai.</Story></section></>}
function Story({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <div className="story-block"><span className="chapter-number">{n}</span><h2>{title}</h2><p>{children}</p></div>}

export function BrewGuide(){const names=['Boil','Add Shams','Sweeten','Add milk','Simmer','Strain & enjoy'];return <><section className="page-hero"><Eyebrow>THE SHAM’S METHOD</Eyebrow><h1>A proper cup.<br/><em>Made your way.</em></h1><p>Begin with the instructions on our pack, then adjust milk, sweetness and strength until the cup tastes like home.</p></section><section className="section brew-guide">{products[0].brewInstructions.map((step,i)=><div key={step}><span>0{i+1}</span><h2>{names[i]}</h2><p>{step}</p></div>)}</section><section className="section brew-note"><div><Eyebrow>YOUR CUP, YOUR CALL</Eyebrow><h2>Room for<br/><em>your own ritual.</em></h2></div><div><p>Make it strong. Make it milky. Sweeten it, or don’t. The best method is the one that brings the cup closest to home.</p><Link className="btn" to="/products/masala-chai">Meet the blend <ArrowUpRight/></Link></div></section></>}

export function Gifting(){return <><section className="section split-hero"><div><Eyebrow>SHAM’S GIFTING</Eyebrow><h1>For the ones<br/>who stay for<br/><em>another cup.</em></h1><p>For personal moments, festive tables and the teams that keep things moving. Tell us what you have in mind.</p><a href="#enquire" className="btn">Enquire about gifting <ArrowUpRight/></a></div><div className="gift-pack"><ImageSlot src={products[0].images[0]} alt="Original Sham’s Masala Chai sachet" ratio="505 / 1080" priority/></div></section><section className="section gift-types">{[['01','Personal moments','For housewarmings, thank-yous and visits that call for another cup.'],['02','Festive tables','A familiar ritual to share with the people around your table.'],['03','Teams & partners','Let us know your quantities and occasion. We’ll discuss the options with you.']].map(([n,title,copy])=><Story key={n} n={n} title={title}>{copy}</Story>)}</section><ContactForm id="enquire" title="What are you planning?"/></>}

export function Contact(){return <><PageHero eyebrow="CONTACT" title="Let’s talk over chai." copy="Questions, gifting enquiries or something you simply want to tell us — write to the Shams team."/><ContactForm title="Send us a note."/></>}
function ContactForm({title,id}:{title:string;id?:string}){
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const subject=encodeURIComponent(`${data.get('type')} from ${data.get('name')}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nEnquiry: ${data.get('type')}\n\n${data.get('message')}`);window.location.href=`mailto:support@shamschai.com?subject=${subject}&body=${body}`};
 return <section className="section contact-form" id={id}><div><Eyebrow>GET IN TOUCH</Eyebrow><h2>{title}</h2><p>Complete the form and we’ll prepare the message in your email app.</p><a className="contact-email" href="mailto:support@shamschai.com">support@shamschai.com</a><a className="text-link" href={whatsappUrl()} target="_blank" rel="noreferrer">Talk to us on WhatsApp <ArrowUpRight/></a></div><form onSubmit={submit}><label>Name<input name="name" autoComplete="name" placeholder="Your name" required/></label><label>Email<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required/></label><label>Enquiry type<select name="type"><option>General question</option><option>Gifting</option><option>Wholesale</option><option>Press</option></select></label><label>Message<textarea name="message" placeholder="How can we help?" rows={5} required/></label><button className="btn" type="submit">Open email app <ArrowRight/></button></form></section>
}

export function Faq(){const qs=[['What pack sizes are available?','Sham’s Masala Chai is available to order in 200 g, 500 g and 1000 g packs.'],['Where can I buy Shams Chai?','Choose your packs on our website and continue on WhatsApp. We confirm availability, final price, delivery and payment with you directly.'],['How should I brew Shams Chai?','Boil 150 ml water, add 1 tsp Masala Chai, sugar to taste and milk as desired. Simmer 3–5 minutes, then strain and enjoy hot.'],['Do you offer gifting?','Tell us your occasion and quantities through our gifting enquiry form. The team will discuss available options with you.'],['What is in the blend?',products[0].ingredients.join(', ')+'. Please contact us with any specific allergen questions before ordering.']];return <><PageHero eyebrow="HELP" title="While the kettle boils." copy="A few useful answers about your next cup."/><section className="section faq">{qs.map(([q,a],i)=><details key={q} open={i===0}><summary><span>0{i+1}</span>{q}</summary><p>{a}</p></details>)}<Link to="/contact" className="text-link">Still have a question? <ArrowRight/></Link></section></>}

export function SearchPage(){const [params,setParams]=useSearchParams();const q=params.get('q')||'';const [term,setTerm]=useState(q);const query=q.toLowerCase();const pp=products.filter(p=>(p.name+p.subtitle+p.flavourNotes.join(' ')).toLowerCase().includes(query));const aa=articles.filter(a=>(a.title+a.category+a.excerpt).toLowerCase().includes(query));const cc=collections.filter(c=>(c.name+c.copy).toLowerCase().includes(query));return <><section className="page-hero search-head"><Eyebrow>SEARCH SHAM’S</Eyebrow><h1>Find your moment.</h1><form onSubmit={e=>{e.preventDefault();setParams({q:term})}}><SearchIcon/><label className="sr-only" htmlFor="search-query">Search products and stories</label><input id="search-query" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Chai, brewing, rain…"/><button type="submit">Search <ArrowRight/></button></form>{q&&<p>{pp.length+aa.length+cc.length} results for “{q}”</p>}</section><section className="section search-results">{q?<>{pp.length>0&&<><h2>The tea</h2><div className="product-grid">{pp.map(p=><ProductCard key={p.id} product={p}/>)}</div></>}{cc.map(c=><Link className="search-row" to={`/collections/${c.slug}`} key={c.slug}><h3>{c.name}</h3><p>{c.copy}</p><ArrowRight/></Link>)}{aa.map(a=><Link className="search-row" to={`/journal/${a.slug}`} key={a.slug}><h3>{a.title}</h3><p>{a.excerpt}</p><ArrowRight/></Link>)}{!pp.length&&!aa.length&&!cc.length&&<p>No results yet. Try “masala”, “family” or “rain”.</p>}</>:<div className="search-suggest">{['Masala','Family','Rain'].map(x=><button onClick={()=>{setTerm(x);setParams({q:x})}} key={x}>{x}<ArrowRight/></button>)}</div>}</section></>}

export function NotFound(){return <section className="not-found section"><Eyebrow>404 / A LITTLE LOST</Eyebrow><h1>The cup isn’t here.</h1><p>The page may have moved, but the chai is still warm.</p><Link to="/" className="btn">Back home <ArrowRight/></Link></section>}
