import {FormEvent,useMemo,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {ArrowRight,ChevronDown,MapPin,Minus,Plus,Search as SearchIcon,ShoppingBag} from 'lucide-react';
import {products,getProduct} from './data/products';
import {articles,collections} from './data/content';
import {useCart} from './context/CartContext';
import ProductCard from './components/ProductCard';
import {ButtonLink,Eyebrow,ImageSlot,money,Reveal,SectionTitle} from './components/ui';

const ProductGrid=({list=products}:{list?:typeof products})=><div className="product-grid">{list.map(p=><ProductCard key={p.id} product={p}/>)}</div>;
const PageHero=({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string})=><section className="page-hero"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{copy&&<p>{copy}</p>}</section>;
const brewSteps=[['01','BOIL','Fresh water, brought to a lively boil.'],['02','ADD SHAMS','Add tea according to the strength you love.'],['03','SWEETEN','Sugar, jaggery or none at all. Your cup.'],['04','ADD MILK','Pour in milk and let the colour deepen.'],['05','SIMMER','Give flavour and conversation a little time.'],['06','STRAIN & ENJOY','Serve hot. Second cups encouraged.']];

export function Home(){return <>
 <section className="hero"><div className="hero-copy"><Reveal><Eyebrow>THE EVERYDAY INDIAN CUP</Eyebrow><h1>CHAI,<br/>THE WAY INDIA<br/><em>REMEMBERS IT.</em></h1><p>Bold tea, familiar flavours and the comfort of a properly brewed Indian cup.</p><div className="actions"><Link className="btn" to="/products">SHOP SHAMS <ArrowRight/></Link><Link className="text-link" to="/our-story">OUR STORY <ArrowRight/></Link></div><small>Founded by Sharmila Krishna</small></Reveal></div><Reveal className="hero-visual"><ImageSlot src="/assets/shams/hero/hero-main.webp" alt="Freshly poured Shams chai" ratio="4 / 5"/></Reveal></section>
 <section className="statement"><Reveal><Eyebrow>THE CUP BETWEEN EVERYTHING</Eyebrow><h2>BEFORE MEETINGS.<br/>AFTER RAIN.<br/>BETWEEN CONVERSATIONS.<br/><em>THERE WAS ALWAYS CHAI.</em></h2><div className="statement-foot"><span>01 — OUR RITUAL</span><p>Shams celebrates the cup that was already part of our lives.</p></div></Reveal></section>
 <section className="section"><SectionTitle eyebrow="OUR CHAI" title="Made for the way you drink it." copy="Four familiar cups. Blended with clarity, strength and no unnecessary fuss."/><ProductGrid/></section>
 <section className="family-band"><div><Eyebrow>THE FAMILY PACK</Eyebrow><h2>FOR HOMES WHERE<br/><em>CHAI RUNS OUT TOO QUICKLY.</em></h2></div><div><div className="pack-options"><span><b>500 g</b><small>EVERYDAY PACK</small></span><span className="selected"><b>1 kg</b><small>FAMILY PACK</small></span></div><p>Made for everyday chai drinkers, second cups and homes where “chai?” is barely a question.</p><Link to="/collections/family-packs" className="btn btn-light">SHOP 1 KG <ArrowRight/></Link></div></section>
 <section className="philosophy"><div><Eyebrow>WHAT MATTERS</Eyebrow><h2>A GOOD CUP<br/>DOESN'T NEED<br/><em>A SPEECH.</em></h2></div><div className="principles">{[['01','TEA WITH STRENGTH','A bold base that stands up beautifully to milk.'],['02','FLAVOUR WITH PURPOSE','Familiar ingredients, balanced for the everyday cup.'],['03','MADE FOR REAL KITCHENS','Simple brewing. Dependable flavour. Chai that fits your life.']].map(x=><Reveal key={x[0]} className="principle"><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></Reveal>)}</div></section>
 <section className="brew-home"><SectionTitle eyebrow="THE SHAMS METHOD" title="Six steps. One proper cup." copy="There is no single correct way to make chai. This is simply where we like to begin."/><div className="brew-strip">{brewSteps.map(s=><div key={s[0]}><span>{s[0]}</span><i>〰</i><b>{s[1]}</b></div>)}</div><Link to="/brew-guide" className="text-link">SEE THE FULL BREW GUIDE <ArrowRight/></Link></section>
 <section className="founder-section"><div><Eyebrow>FOUNDER</Eyebrow><blockquote>“I didn't want to reinvent chai.<br/><em>I wanted to honour why we love it.</em>”</blockquote><p>— Sharmila Krishna<br/><small>FOUNDER, SHAMS CHAI</small></p><Link to="/founder" className="text-link">MEET SHARMILA <ArrowRight/></Link></div></section>
 <section className="section moments"><SectionTitle eyebrow="CHAI, AS IT HAPPENS" title="Every cup has a setting."/><div className="moment-grid">{[['HOME','The first sound in the kitchen.','lifestyle-home.webp'],['RAIN','A slower evening by the window.','lifestyle-rain.webp'],['TOGETHER','Conversations that outlast the kettle.','lifestyle-together.webp']].map((m,i)=><Reveal key={m[0]} className={`moment m${i}`}><ImageSlot src={`/assets/shams/lifestyle/${m[2]}`} alt={m[0]} ratio={i===1?'3 / 4':'4 / 5'}/><span>0{i+1}</span><h3>{m[0]}</h3><p>{m[1]}</p></Reveal>)}</div></section>
 <section className="retail-preview"><div><Eyebrow>WHERE TO BUY</Eyebrow><h2>YOUR SHAMS,<br/><em>WHEREVER YOU SHOP.</em></h2><p>Our direct store comes first. Your favourite everyday marketplaces are next.</p><Link className="btn btn-light" to="/where-to-buy">EXPLORE STOCKISTS <ArrowRight/></Link></div><div className="market-list">{['AMAZON INDIA','BLINKIT','ZEPTO','BIGBASKET'].map(x=><span key={x}>{x}<small>COMING SOON</small></span>)}</div></section>
 <section className="gifting-preview"><div><Eyebrow>SHAMS GIFTING</Eyebrow><h2>SOME CONVERSATIONS<br/><em>DESERVE BETTER CHAI.</em></h2><p>For festivals, milestones, teams and the people who always stay for another cup.</p><Link to="/gifting" className="text-link">DISCOVER GIFTING <ArrowRight/></Link></div><ImageSlot src="/assets/shams/gifting/gift-main.webp" alt="Shams gifting" ratio="16 / 10"/></section>
 <section className="section journal-preview"><SectionTitle eyebrow="THE SHAMS JOURNAL" title="Notes on a shared ritual."/><div className="article-grid">{articles.slice(0,3).map(a=><ArticleCard key={a.slug} a={a}/>)}</div><Link to="/journal" className="text-link">READ ALL STORIES <ArrowRight/></Link></section>
 <section className="home-news"><Eyebrow>NOTES FROM SHAMS</Eyebrow><h2>GOOD CHAI.<br/><em>GOOD READING.</em></h2><p>Occasional letters about brewing, daily rituals and what we're making next.</p><form><input placeholder="EMAIL ADDRESS"/><button>JOIN THE LIST <ArrowRight/></button></form><small>Thoughtful notes only. Unsubscribe whenever you like.</small></section>
 </>}

export function ProductsPage(){const [sort,setSort]=useState('Featured');const list=useMemo(()=>[...products].sort((a,b)=>sort==='Price Low to High'?a.variants[0].price-b.variants[0].price:sort==='Price High to Low'?b.variants[0].price-a.variants[0].price:0),[sort]);return <><PageHero eyebrow="SHOP SHAMS" title="FIND YOUR CHAI." copy="Strong, spiced, gingery or aromatic — there is a Shams for every kind of chai person."/><section className="catalog"><div className="filterbar"><button>FILTER <span>＋</span></button><div>{['Blend','Pack Size','Flavour','Availability','Price'].map(x=><button key={x}>{x}<ChevronDown/></button>)}</div><label>SORT BY <select value={sort} onChange={e=>setSort(e.target.value)}>{['Featured','Newest','Price Low to High','Price High to Low'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="results"><span>{list.length} PRODUCTS</span><ProductGrid list={list}/></div></section></>}

export function ProductPage(){const {slug}=useParams();const p=getProduct(slug);const [vi,setVi]=useState(0);const [q,setQ]=useState(1);const [tab,setTab]=useState('ABOUT THIS CHAI');const c=useCart();if(!p)return <NotFound/>;const v=p.variants[vi];const tabs:{[k:string]:string|JSX.Element}={'ABOUT THIS CHAI':p.description,'FLAVOUR':p.flavourNotes.join(' · '),'INGREDIENTS':p.ingredients.join(', '),'HOW TO BREW':<ol>{p.brewInstructions.map(x=><li key={x}>{x}</li>)}</ol>,'PRODUCT DETAILS':`Pack size: ${v.weight}. SKU: ${v.sku}. Final regulatory and manufacturer details to be supplied before launch.`};return <><section className="pdp"><div className="pdp-gallery"><ImageSlot src={p.images[0]} alt={p.name} ratio="1 / 1"/><ImageSlot src={p.images[1]} alt={`${p.name} brewed`} ratio="4 / 5"/></div><div className="pdp-info"><div className="breadcrumb"><Link to="/products">SHOP</Link> / {p.name.toUpperCase()}</div><Eyebrow>EVERYDAY CHAI</Eyebrow><h1>{p.name}</h1><p className="pdp-sub">{p.subtitle}</p><div className="pdp-price">{money(v.price)} <small>INCLUSIVE OF TAXES</small></div><p>{p.description}</p><label className="choice-label">CHOOSE YOUR PACK <span>{v.weight}</span></label><div className="pdp-variants">{p.variants.map((x,i)=><button onClick={()=>setVi(i)} className={vi===i?'active':''} key={x.sku}><b>{x.weight}</b><span>{i?'FAMILY PACK':'EVERYDAY PACK'}</span><small>{money(x.price)}</small></button>)}</div><div className="pdp-actions"><div className="quantity"><button onClick={()=>setQ(Math.max(1,q-1))}><Minus/></button>{q}<button onClick={()=>setQ(q+1)}><Plus/></button></div><ButtonLink onClick={()=>c.add(p,v,q)}>ADD TO CART — {money(v.price*q)}</ButtonLink></div><button className="buy-now">BUY NOW — COMING SOON</button><div className="delivery"><MapPin/><div><b>CHECK DELIVERY</b><span>Enter your pincode for an estimate</span></div><input maxLength={6} placeholder="000000"/></div>{Object.keys(tabs).map(x=><div className="pdp-tab" key={x}><button onClick={()=>setTab(tab===x?'':x)}>{x}<span>{tab===x?'−':'+'}</span></button>{tab===x&&<div>{tabs[x]}</div>}</div>)}</div></section><section className="section recs"><SectionTitle eyebrow="KEEP THE KETTLE ON" title="You may also like."/><ProductGrid list={products.filter(x=>x.id!==p.id).slice(0,3)}/></section><div className="mobile-atc"><span><b>{p.name}</b>{v.weight} · {money(v.price)}</span><button onClick={()=>c.add(p,v,q)}>ADD TO CART</button></div></>}

export function CollectionsPage(){return <><PageHero eyebrow="SHOP BY MOOD" title="OUR COLLECTIONS." copy="However your home makes chai, there is a Shams blend made to meet it."/><section className="collection-grid">{collections.map((x,i)=><Link to={`/collections/${x.slug}`} key={x.slug}><span>0{i+1}</span><h2>{x.name}</h2><p>{x.copy}</p><ArrowRight/></Link>)}</section></>}
export function CollectionPage(){const {slug}=useParams();const col=collections.find(x=>x.slug===slug);const list=slug==='family-packs'?products.map(p=>({...p,variants:[p.variants[1],p.variants[0]]})):products;return <><PageHero eyebrow="COLLECTION" title={(col?.name||'Our Chai').toUpperCase()+'.'} copy={col?.copy}/><section className="section"><ProductGrid list={list}/></section></>}

export function OurStory(){return <><PageHero eyebrow="OUR STORY" title="CHAI WAS ALREADY HERE." copy="In our kitchens. Between our conversations. Waiting at the end of a long day. Shams began with respect for that everyday cup."/><section className="story-grid"><div className="story-copy"><Story n="01" title="WHY SHAMS?">The chai we grew up with, made for the lives we live now. Familiar, dependable and presented with the care an everyday ritual deserves.</Story><Story n="02" title="BUILT BY SHARMILA">Sharmila Krishna created Sham’s from a simple belief: the chai already woven into our everyday lives deserves to be made with intention, honesty and genuine care.</Story></div><ImageSlot src="/assets/shams/lifestyle/lifestyle-home.webp" alt="Chai at home" ratio="4 / 5"/></section><section className="story-dark"><Story n="03" title="THE EVERYDAY CUP">We believe daily things deserve good design, clear choices and consistent quality. Not because chai needs changing — because it deserves attention.</Story><Story n="04" title="WHAT COMES NEXT">More considered blends, easier ways to find Shams, and a growing journal of the ways India drinks chai.</Story></section></>}
function Story({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <div className="story-block"><span>{n}</span><h2>{title}</h2><p>{children}</p></div>}

export function Founder(){return <><section className="founder-hero"><div><Eyebrow>FOUNDER, SHAMS CHAI</Eyebrow><h1>SHARMILA<br/><em>KRISHNA.</em></h1><p>Building a modern Indian chai brand around the cup that was already ours.</p></div></section><section className="founder-note"><Eyebrow>A NOTE FROM SHARMILA</Eyebrow><blockquote>“I didn't want to reinvent chai.<br/><em>I wanted to honour why we love it.”</em></blockquote><p>Founder-approved note and biographical copy will be placed here before launch. This page intentionally avoids inventing personal history or business claims.</p></section><section className="founder-chapters">{['WHY SHAMS','WHY CHAI MATTERS','BUILDING A MODERN INDIAN BRAND','WHAT COMES NEXT'].map((x,i)=><Story key={x} n={`0${i+1}`} title={x}>Editable founder copy. Use this section for Sharmila’s own perspective, story and plans once final wording is supplied.</Story>)}</section></>}

export function BrewGuide(){return <><PageHero eyebrow="THE SHAMS METHOD" title="MAKE IT YOURS." copy="Chai is instinct before it is instruction. Begin here, then adjust until the cup tastes like home."/><section className="brew-guide">{brewSteps.map(s=><div key={s[0]}><span>{s[0]}</span><i>〰</i><h2>{s[1]}</h2><p>{s[2]}</p></div>)}</section><section className="brew-note"><div><Eyebrow>YOUR CUP, YOUR CALL</Eyebrow><h2>STRONGER?<br/>SIMMER LONGER.</h2></div><p>Exact quantities remain configurable by blend. Start with one cup of water, tea to your preferred strength, milk and sweetener to taste. Adjust without apology.</p></section></>}

export function Gifting(){return <><section className="split-hero"><div><Eyebrow>SHAMS GIFTING</Eyebrow><h1>SOME CONVERSATIONS<br/><em>DESERVE BETTER CHAI.</em></h1><p>Thoughtful chai gifts for personal moments, festive tables and the teams that keep things moving.</p><a href="#enquire" className="btn">ENQUIRE NOW <ArrowRight/></a></div><ImageSlot src="/assets/shams/gifting/gift-main.webp" alt="Shams chai gift composition" ratio="4 / 5"/></section><section className="gift-types">{[['01','PERSONAL GIFTING','For housewarmings, thank-yous and visits that call for more than flowers.'],['02','FESTIVE GIFTING','Warm, considered boxes for the people around your table.'],['03','CORPORATE GIFTING','Flexible quantities and tasteful presentation for teams and partners.']].map(x=><Story key={x[0]} n={x[0]} title={x[1]}>{x[2]}</Story>)}</section><ContactForm id="enquire" title="TELL US WHAT YOU'RE PLANNING."/></>}

export function WhereToBuy(){return <><PageHero eyebrow="FIND SHAMS" title="YOUR SHAMS, WHEREVER YOU SHOP." copy="Shop direct when our store opens. We’re working to bring Shams to the places you already buy your everyday essentials."/><section className="direct-card"><div><Eyebrow>DIRECT FROM SHAMS</Eyebrow><h2>The full collection,<br/>from our shelf to yours.</h2></div><Link to="/products" className="btn btn-light">SHOP ALL CHAI <ArrowRight/></Link></section><section className="market-grid">{['Amazon India','Flipkart','Blinkit','Zepto','Swiggy Instamart','BigBasket'].map(x=><div key={x}><h3>{x}</h3><span>COMING SOON</span></div>)}</section><p className="truth-note">Marketplace links and availability will be added only after official listings are confirmed.</p></>}

function ArticleCard({a}:{a:typeof articles[0]}){return <Link className="article-card" to={`/journal/${a.slug}`}><ImageSlot src={a.image} alt={a.title} ratio="4 / 3"/><span>{a.category}</span><h3>{a.title}</h3><p>{a.excerpt}</p><b>READ STORY <ArrowRight/></b></Link>}
export function Journal(){return <><PageHero eyebrow="THE SHAMS JOURNAL" title="STORIES TO POUR OVER." copy="On chai, home, habit and the small moments that make a day feel familiar."/><section className="journal-grid">{articles.map(a=><ArticleCard key={a.slug} a={a}/>)}</section></>}
export function Article(){const {slug}=useParams();const a=articles.find(x=>x.slug===slug);if(!a)return <NotFound/>;return <article className="article"><header><Eyebrow>{a.category}</Eyebrow><h1>{a.title}</h1><p>{a.excerpt}</p><span>SHAMS JOURNAL · 5 MIN READ</span></header><ImageSlot src={a.image} alt={a.title} ratio="16 / 9"/><div className="article-body"><p className="lead">There are ordinary cups, and then there are cups that seem perfectly matched to the moment. Chai has always known the difference.</p><p>This editorial article is a considered preview. Final long-form copy should be reviewed and approved by the Shams team before launch, with any factual or cultural references checked at source.</p><h2>A ritual with room for everyone</h2><p>Every home has its own order of operations: water first or milk first, ginger crushed or sliced, cardamom counted or measured by instinct. The differences are not flaws in the recipe. They are the point.</p><blockquote>Chai is less a single recipe than a language every home speaks in its own accent.</blockquote><p>At Shams, we want to celebrate that shared familiarity while leaving plenty of room for the way you already make yours.</p></div></article>}

export function Contact(){return <><PageHero eyebrow="CONTACT" title="LET'S TALK OVER CHAI." copy="Questions, gifting enquiries or something you simply want to tell us — write to the Shams team."/><ContactForm title="SEND US A NOTE."/></>}
function ContactForm({title,id}:{title:string;id?:string}){
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('name')||'');const email=String(data.get('email')||'');const type=String(data.get('type')||'General question');const message=String(data.get('message')||'');const subject=encodeURIComponent(`${type} from ${name}`);const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\nEnquiry: ${type}\n\n${message}`);window.location.href=`mailto:support@shamschai.com?subject=${subject}&body=${body}`};
 return <section className="contact-form" id={id}><div><Eyebrow>GET IN TOUCH</Eyebrow><h2>{title}</h2><p>Have a question about Sham’s, gifting or partnerships? Complete the form and we’ll prepare the message in your email app.</p><a className="contact-email" href="mailto:support@shamschai.com">support@shamschai.com</a></div><form onSubmit={submit}><label>NAME<input name="name" placeholder="Your name" required/></label><label>EMAIL<input name="email" type="email" placeholder="you@example.com" required/></label><label>ENQUIRY TYPE<select name="type"><option>General question</option><option>Gifting</option><option>Wholesale</option><option>Press</option></select></label><label>MESSAGE<textarea name="message" placeholder="How can we help?" rows={5} required/></label><button className="btn" type="submit">OPEN EMAIL APP <ArrowRight/></button></form></section>
}

export function Faq(){const qs=[['What pack sizes are available?','Every Shams blend is designed to be offered in 500 g Everyday Packs and 1 kg Family Packs.'],['Where can I buy Shams Chai?','Direct and marketplace purchasing will be enabled when official availability is confirmed. See Where to Buy for current status.'],['How should I brew Shams Chai?','Visit our Brew Guide for the simple six-step Shams method, then adjust milk, sweetness and strength to your taste.'],['Do you offer gifting?','Personal, festive and corporate gifting are planned. Use the gifting enquiry form to tell us what you need.'],['Are ingredients and allergen details final?','No. Final ingredient, allergen, manufacturer and regulatory information must be supplied and approved before launch.']];const [open,setOpen]=useState(0);return <><PageHero eyebrow="HELP" title="FREQUENTLY ASKED." copy="A few useful answers while the kettle comes to a boil."/><section className="faq">{qs.map((q,i)=><div key={q[0]}><button onClick={()=>setOpen(open===i?-1:i)}><span>0{i+1}</span>{q[0]}<b>{open===i?'−':'+'}</b></button>{open===i&&<p>{q[1]}</p>}</div>)}</section></>}

export function SearchPage(){const [params,setParams]=useSearchParams();const q=params.get('q')||'';const [term,setTerm]=useState(q);const query=q.toLowerCase();const pp=products.filter(p=>(p.name+p.subtitle+p.flavourNotes.join(' ')).toLowerCase().includes(query));const aa=articles.filter(a=>(a.title+a.category+a.excerpt).toLowerCase().includes(query));const cc=collections.filter(c=>(c.name+c.copy).toLowerCase().includes(query));return <><section className="search-head"><Eyebrow>SEARCH SHAMS</Eyebrow><form onSubmit={e=>{e.preventDefault();setParams({q:term})}}><SearchIcon/><input autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder="What are you looking for?"/><button>SEARCH</button></form>{q&&<p>{pp.length+aa.length+cc.length} results for “{q}”</p>}</section>{q?<section className="search-results">{pp.length>0&&<><h2>CHAI</h2><ProductGrid list={pp}/></>}{cc.length>0&&<><h2>COLLECTIONS</h2>{cc.map(c=><Link className="search-row" to={`/collections/${c.slug}`} key={c.slug}><span>{c.name}</span><p>{c.copy}</p><ArrowRight/></Link>)}</>}{aa.length>0&&<><h2>JOURNAL</h2>{aa.map(a=><Link className="search-row" to={`/journal/${a.slug}`} key={a.slug}><span>{a.title}</span><p>{a.excerpt}</p><ArrowRight/></Link>)}</>}{!pp.length&&!aa.length&&!cc.length&&<div className="no-results"><h2>No results yet.</h2><p>Try “masala”, “ginger”, “family” or “rain”.</p></div>}</section>:<div className="search-suggest"><h2>TRY SEARCHING</h2>{['MASALA CHAI','1 KG FAMILY PACKS','HOW TO BREW','GIFTING'].map(x=><button onClick={()=>{setTerm(x);setParams({q:x})}} key={x}>{x}<ArrowRight/></button>)}</div>}</>}

export function CartPage(){const c=useCart();return <><PageHero eyebrow="YOUR ORDER" title="YOUR CART." copy={c.count?'A good cup is getting closer.':'Your cart is currently empty.'}/>{c.items.length?<section className="cart-page"><div>{c.items.map(i=><div className="cart-page-line" key={i.variant.sku}><ImageSlot src={i.product.images[0]} alt={i.product.name} ratio="1 / 1"/><div><Link to={`/products/${i.product.slug}`}><h3>{i.product.name}</h3></Link><span>{i.variant.weight} · {i.variant.sku}</span><div className="quantity"><button onClick={()=>c.update(i.variant.sku,i.quantity-1)}><Minus/></button>{i.quantity}<button onClick={()=>c.update(i.variant.sku,i.quantity+1)}><Plus/></button></div><button className="remove" onClick={()=>c.remove(i.variant.sku)}>REMOVE</button></div><b>{money(i.variant.price*i.quantity)}</b></div>)}</div><aside><h3>ORDER SUMMARY</h3><p><span>Subtotal</span><b>{money(c.subtotal)}</b></p><p><span>Shipping</span><b>Calculated at checkout</b></p><hr/><p><span>TOTAL</span><strong>{money(c.subtotal)}</strong></p><button className="btn">CHECKOUT — COMING SOON</button><small>No payment will be collected in this preview.</small></aside></section>:<div className="empty-page"><ShoppingBag/><h2>The kettle is on.</h2><Link to="/products" className="btn">SHOP CHAI <ArrowRight/></Link></div>}</>}
export function Account(){return <><PageHero eyebrow="ACCOUNT" title="WELCOME BACK." copy="Account sign-in will be connected when the commerce backend is selected."/><section className="account-card"><h2>SIGN IN</h2><label>EMAIL<input type="email" placeholder="you@example.com"/></label><label>PASSWORD<input type="password" placeholder="••••••••"/></label><button className="btn">SIGN IN — COMING SOON</button><p>New to Shams? Account creation will be available at launch.</p></section></>}
export function NotFound(){return <section className="not-found"><span>404</span><h1>THE CUP ISN'T HERE.</h1><p>The page may have moved, but the chai is still warm.</p><Link to="/" className="btn">BACK HOME <ArrowRight/></Link></section>}
